server:
  port: 8081

spring:
  datasource:
    # 운영 DB 주소
    url: jdbc:postgresql://${PROD_DB_URL}:5432/${PROD_DB}?stringtype=unspecified&reWriteBatchedInserts=true
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}

  jpa:
    show-sql: false # 운영에선 로그 끔

  kafka:
    # 운영 카프카 주소
    bootstrap-servers: ${PROD_KAFKA_URL}:9092